"""Type stubs for `toklab._native`. Hand-written; keep in sync with
`crates/toklab-py/src/lib.rs`."""

from __future__ import annotations

__version__: str

class ToklabError(Exception):
    """Raised on tiktoken-rs failures."""

class Tokenizer:
    @staticmethod
    def for_model(model: str) -> Tokenizer: ...
    @staticmethod
    def for_encoding(name: str) -> Tokenizer: ...
    @property
    def encoding_name(self) -> str: ...
    def count(self, text: str) -> int: ...
    def count_many(self, texts: list[str], parallel: bool = False) -> list[int]: ...
    def encode(self, text: str) -> list[int]: ...
    def decode(self, tokens: list[int]) -> str: ...
    def fits(self, text: str, *, budget: int) -> bool: ...
    def truncate_to(self, text: str, *, budget: int) -> str: ...
    def __repr__(self) -> str: ...
